model:
  hidden_dim: 256
  num_layers: 8
  num_charts: 4
  c_pe_degree: 1
  t_pe_degree: 4
  s_pe_degree: 4
train:
  name: bunny
  mesh_path: data/stanford-bunny.obj
  epochs: 1
  iters: 1000
  G_num: 5000
  T_num: 5000
  seed: 37
  use_wandb: False
  save_interval: 200
loss:
  three_two_three: 1
  two_three_two: 1
  entropy: 0.04
  surface: 10
  cluster: 0.5
  conformal: 0.4
  stretch: 0.1
  texture: 0
optimizer:
  nuvo_lr: 1e-4
  sigma_lr: 0.1
  normal_grids_lr: 0.04
  rgb_grids_lr: 0.04
# ckpt: output/checkpoint_0_499.ckpt